### ISSUE TITLE
Can't install via npm

### ISSUE THREAD

**Issue by samueldelesque** [duosecurity/duo_web_sdk#2]
Installing via NPM throws an error: 
```
npm ERR! addLocal Could not install /var/folders/85/hc36n4312rq8q55shdw15zz50p1hct/T/npm-6968-fad008ab/git-cache-9837df60/d43c4bad165cee70d277a986d23eee336426d4cf
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "https://github.com/duosecurity/duo_web_sdk.git" "--save"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2

npm ERR! Invalid version: "2.5"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

I believe it could be because the version name is not semantic...

Thanks!

**Comment by samueldelesque** [comment]
PS: This is confirmed. https://github.com/carbonblack/duo_web_sdk/commit/ae6383e2f2ec7e4a65510f472c2bba5e2e285385

**Comment by subyraman** [comment]
Thanks! Will put up a fix ASAP.

**Comment by subyraman** [comment]
This has been fixed in the latest master. `npm install https://github.com/duosecurity/duo_web_sdk.git --save
` will work now. Thanks for your patience!
