### ISSUE TITLE
Nothing posted to post_action URL when running iframe from a file:// URL

### ISSUE THREAD

**Issue by mconigliaro** [duosecurity/duo_web_sdk#24]
I have the iframe running in a local file. Everything seems to load fine, and the authentication buttons work (I get push notifications on my phone, and I get the `Success! Logging you in...` message), but I see an error in the console:

- Chrome: `Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').`
- Firefox: `Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘null’) does not match the recipient window’s origin (‘null’).`
- Safari: `Unable to post message to file://. Recipient has origin null.`

I don't see anything getting posted to the `post_action` URL, so I believe this might be why my Okta integration isn't working.

There's a hint [here](https://stackoverflow.com/questions/59158823/unable-to-post-message-to-file-recipient-has-origin-null-on-cordova-wkwebvi#59821928) that maybe I need to serve this file from a webserver, but I wanted to make sure I wasn't doing something dumb first.

**Comment by AaronAtDuo** [comment]
My first hunch is that this is some kind of CORS or XSS protection, which we've fought with many times.  It's a big part of why we've moved away from the iframe-based prompt in favor of our redirect-based OIDC-ish Universal Prompt.

Unfortunately, I don't have any specific suggestions for a workaround at the moment.  If you're willing to share your HTML we can try to reproduce the issue and see if anything comes to mind.

**Comment by mconigliaro** [comment]
My HTML is essentially the same as [this Okta example](https://developer.okta.com/docs/reference/api/authn/#sample-for-duo-iframe). I've confirmed that if I serve if from a web server, everything works fine. So I guess I have my answer!
