### ISSUE TITLE
npm audit critical security issue

### ISSUE THREAD

**Issue by ghost** [duosecurity/duo_web_sdk#27]
Our npm audit shows this warning. Could you help confirm if this vulnerability?

```
duo_web_sdk
Severity: critical
Malware in duo_web_sdk - https://github.com/advisories/GHSA-gwjw-ph82-w683
No fix available
node_modules/duo_web_sdk
```

<img width="1180" alt="Screen Shot 2022-06-23 at 11 14 22 AM" src="https://user-images.githubusercontent.com/61473647/175366839-d4bc40e5-9384-4908-ae44-ef2a64bb8727.png">

**Comment by AaronAtDuo** [comment]
I believe this advisory is referring to https://www.npmjs.com/package/duo_web_sdk.  That package is not published by Duo Security - we publish packages only under our NPM organization https://www.npmjs.com/org/duosecurity.  While we do have this GitHub repository, named duo_web_sdk, it is not the source of the NPM package in question.

**Comment by AaronAtDuo** [comment]
Closing out, as we've established the vulnerable library is unrelated to this repo.
