### ISSUE TITLE
Add a way for host application to get iframe body's height

### ISSUE THREAD

**Issue by kspearrin** [duosecurity/duo_web_sdk#6]
Using the iframe at it's full width does not normally pose any issues, however, when using it in width constrained scenarios such as mobile devices, the height of the iframe content often changes. This is problematic because the host page cannot determine when this content changes in order make appropriate adjustments to the height of the iframe. This results in two problems:

- You make the height of the iframe conservatively large which leaves unwanted whitespace in many scenarios. Ex:

![image](https://user-images.githubusercontent.com/1190944/27402939-8b7b825a-5696-11e7-8957-59ac5030df09.png)

- Or you make the iframe too small and end up with users not being able to see the needed content. Ex:

![image](https://user-images.githubusercontent.com/1190944/27403708-6923a446-5699-11e7-8bf3-c55ff872a1f3.png)

Some browsers like Safari do not even show scrollbars so it makes it almost impossible to know there is more content to scroll to, leading to a confused user.

Solution
========

Use messages to post back the height of the iframe body each time content changes. Examples: https://stackoverflow.com/a/22991952/1090359

I'd recommend the `MutationObserver` solution.

Finally, add a callback to `DuoWebSDK.init()` so that host application can react to the new height and apply it appropriately.

Ex:

```
Duo.init({
    // ...
    content_changed: function (height) {
        // ...
    }
});
```

**Comment by adrikim** [comment]
Hey Kyle, thanks for bringing this to our attention too! This issue is also being tracked right now and we'll see what we can do about it- hopefully your solution plays nicely with testing, but if not, we'll see if there's another way.

**Comment by AaronAtDuo** [comment]
Closing out this old issue
