### ISSUE TITLE
Duo.init() can only initialize a single iframe per doc ready

### ISSUE THREAD

**Issue by kspearrin** [duosecurity/duo_web_sdk#7]
Issue
==========

Consider a SPA where Duo Web SDK factory initialization is only done once (on dom ready).

I can only call `Duo.init()` once. If I call `Duo.init()` any other time, the [cached `iframe` variable](https://github.com/duosecurity/duo_web_sdk/blob/master/index.js#L259) is reused, which may no longer exists on the page. Therefore the new `iframe` dom element fails to be setup and load any content.

Example
=========

This can be illustrated in a simple AngularJS app as follows (also see attached .zip for runnable example):

[duo-web-spa-issue.zip](https://github.com/duosecurity/duo_web_sdk/files/1098697/duo-web-spa-issue.zip)

```
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
    <script src="duo.js"></script>

    <script>
        var myApp = angular.module('myApp', []);
        myApp.controller('myController', function ($scope, $timeout) {
            $scope.loggedIn = false;
            $scope.showLogin = false;

            $scope.login = function () {
                $scope.loggedIn = false;
                $scope.showLogin = true;

                $timeout(function () {
                    Duo.init({
                        host: 'api-4c50a4b2.duosecurity.com',
                        sig_request: 'TX|YWI0OTgxNDg=|cb88d6f90:APP|YWI2NDU0NDg=|10f4d22a',
                        submit_callback: function (theForm) {
                            console.log(theForm);
                        }
                    });
                }, 100);
            };

            $scope.logout = function () {
                $scope.loggedIn = false;
                $scope.showLogin = false;
            };

            $scope.dash = function () {
                $scope.loggedIn = true;
                $scope.showLogin = false;
            };
        });
    </script>

    <style>
        body {
            background-color: #eeeeee;
            font-size: 14px;
            font-family: Arial;
            overflow-y: auto;
            padding: 0;
            margin: 0;
        }

        iframe {
            width: 400px;
            height: 500px;
        }
    </style>
</head>
<body>
    <div ng-controller="myController" class="container">
        <div ng-if="!loggedIn && !showLogin">
            Welcome<br />
            <button type="button" ng-click="login()">Let's Log In</button>
        </div>
        <div ng-if="showLogin">
            Log In With Duo<br />
            <iframe id="duo_iframe"></iframe><br />
            <button type="button" ng-click="dash()">Go To Dashboard</button>
        </div>
        <div ng-if="loggedIn">
            Logged in<br />
            <button type="button" ng-click="logout()">Log out</button>
        </div>
    </div>
</body>
</html>
```

The first load of `showLogin` will present the proper `iframe` contents (note that access denied is expected since I am not using a real signature, but illustrates that the `iframe` loads the proper page).

![image](https://user-images.githubusercontent.com/1190944/27495522-38b877f4-5820-11e7-86d3-1ef804c15fd4.png)

If you click Go To Dashboard, then Log Out, then Log In again `Duo.init()` will again be called. This time no content loads from the `iframe` (`iframe` has no `src` according to dev tools).

![image](https://user-images.githubusercontent.com/1190944/27495563-675df462-5820-11e7-8e22-0d378bef759a.png)

Possible Solution
======

Expose a way for implementation to clear the `iframe` variable in the Duo factory?

**Comment by adrikim** [comment]
Hey Kyle, thanks for bringing up the issue- having the example is especially helpful. We're tracking the issue now and are looking into it, so someone should get back to you soon.

**Comment by kspearrin** [comment]
Thanks @adrikim .

Our workaround for now is to use a modified version of [`index.js`](https://github.com/duosecurity/duo_web_sdk/blob/master/index.js) with [line 259](https://github.com/duosecurity/duo_web_sdk/blob/master/index.js#L259) changed in order for force a new iframe each time:

```
if (false && iframe) {
    ready();
} else {
```

**Comment by mehtadev17** [comment]
Any updates on this issue?

**Comment by gerwim** [comment]
Thanks @kspearrin. This is actually what I needed, was digging around the files already. Cheers!

**Comment by ktschmidt** [comment]
Has there been any progress on this?  I am just starting to look at integration my SPA with Duo and ran into this right away.

The workaround works, but throwing a "false && " in existing code doesn't feel like the real solution and I hate to be changing Duo code to make it work.  @adrikim is that what is expected for each customer using Duo in a SPA?  The Duo-Web-v2.js is something we should feel comfortable making changes to and having our own copy?

**Comment by kspearrin** [comment]
I think someone did a PR here: https://github.com/duosecurity/duo_web_sdk/pull/8

**Comment by Cole-Beckwith-SP** [comment]
Running into this as well. Looks like #8 has been inactive for a while. Are there plans to make changes regarding this issue?

**Comment by mehtadev17** [comment]
Opened #12  that should address the comments on #8

**Comment by justcolin** [comment]
@kspearrin, @Cole-Beckwith-SP, @mehtadev17, @gerwim and @ktschmidt: We just posted version 2.7 of the Duo Web SDK to address this problem. You should now be able to re-call `init()` after any time you add a new iframe in a single page application. Thank you again @kspearrin for doing such a thorough initial writeup in your initial post; it really helped make sure we were understanding everyone's needs.

If you experience any more issue please feel free to post another issue or a PR.

Cheers!
Colin

**Comment by kspearrin** [comment]
Thanks @justcolin . I just tested it and it works great.
